/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    colors: {
      blue: "#001F3D",
      lightblue: "#1e3a8a",
      dashblue: "#0e1851",
      orange: "#ffc61a",
      black: "#000000",
      gray: "#595959",
      lightgray: "#a6a6a6",
      indigo: "#4b0082",
      white: "#ffffff",
      yellow: "#FFCB05",
      lightyellow: "#fbbf24",
      lightgreen: "#bbf7d0",
      darkgreen: "#34d399",
      lightbluee: "#bae6fd",
      darkblue: "#3b82f6",
      lightpink: "#fbcfe8",
      darkpink: "#fb7185",
    },
    screens: {
      xs: "280px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    extend: {},
  },
  plugins: [require("@tailwindcss/forms")],
};
